export const LOAD_CURRENCIES = "LOAD_CURRENCIES";
export const FETCH_CURRENCIES = "FETCH_CURRENCIES";
export const SET_CURRENCIES_LOAD_ERROR = "SET_CURRENCIES_LOAD_ERROR";
export const SET_BASE_CURRENCY = "SET_BASE_CURRENCY;";
