export const LOAD_CURRENCIES = "LOAD_CURRENCIES";
export const FETCH_CURRENCIES = "FETCH_CURRENCIES";
export const SET_CURRENCIES_LOAD_ERROR = "SET_CURRENCIES_LOAD_ERROR";
export const SET_BASE_CURRENCY = "SET_BASE_CURRENCY";
export const ADD_SELECTED_CURRENCY = "ADD_SELECTED_CURRENCY";
export const REMOVE_SELECTED_CURRENCY = "REMOVE_SELECTED_CURRENCY";